package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/averycrespi/agent-tools/mcp-gateway/internal/contract"
)

func main() {
	check := flag.String("check", "", "verify an existing generated artifact")
	output := flag.String("output", "", "write the generated artifact")
	flag.Parse()
	if flag.NArg() != 0 || (*check == "") == (*output == "") {
		fmt.Fprintln(os.Stderr, "usage: generate-development-contract (--check PATH | --output PATH)")
		os.Exit(2)
	}

	limit, ok := contract.FixedLimitByName("api_json_body_bytes")
	if !ok || limit.Maximum < 1 {
		fmt.Fprintln(os.Stderr, "api_json_body_bytes is absent or invalid")
		os.Exit(1)
	}
	generated := []byte(fmt.Sprintf("// Code generated by generate-development-contract.go; DO NOT EDIT.\nexport const API_JSON_BODY_MAX_BYTES = %d;\n", limit.Maximum))

	if *check != "" {
		current, err := os.ReadFile(*check)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read generated contract: %v\n", err)
			os.Exit(1)
		}
		if !bytes.Equal(current, generated) {
			fmt.Fprintln(os.Stderr, "generated development contract is out of date")
			os.Exit(1)
		}
		return
	}

	if err := writeAtomic(*output, generated); err != nil {
		fmt.Fprintf(os.Stderr, "write generated contract: %v\n", err)
		os.Exit(1)
	}
}

func writeAtomic(path string, content []byte) error {
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".development-contract-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}()
	if err := temporary.Chmod(0o644); err != nil {
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
