package remote

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"io"
	"net"
	"net/http"
	"net/netip"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/averycrespi/agent-tools/agent-gateway/internal/contract"
	"github.com/averycrespi/agent-tools/agent-gateway/internal/httppolicy"
)

// ProxyAddress is a single-use resolved destination, never a pooled permission.
// Policy evaluates Facts before receipt confirmation. Dial rechecks exclusions
// against the current composition-owned listener inventory without resolving.
type ProxyAddress struct {
	factory     *Factory
	destination httppolicy.Destination
	facts       httppolicy.AddressFacts
	listeners   func() []netip.AddrPort
	used        atomic.Bool
}

func (f *Factory) ResolveProxy(ctx context.Context, d httppolicy.Destination, listeners func() []netip.AddrPort) (*ProxyAddress, error) {
	if d.Host() == "" || d.Port() == 0 || listeners == nil {
		return nil, ErrAddressPolicy
	}
	ctx, cancel := context.WithTimeout(ctx, contract.HTTPProxyDialTimeout)
	defer cancel()
	var addresses []netip.Addr
	if ip, err := netip.ParseAddr(d.Host()); err == nil {
		addresses = []netip.Addr{ip}
	} else {
		var err error
		addresses, err = f.resolver.LookupNetIP(ctx, "ip", d.Host())
		if err != nil {
			return nil, ErrAddressPolicy
		}
	}
	if len(addresses) == 0 || len(addresses) > contract.HTTPAddressFacts {
		return nil, ErrAddressPolicy
	}
	owned := listeners()
	if len(owned) > contract.HTTPAddressFacts {
		return nil, ErrAddressPolicy
	}
	return &ProxyAddress{factory: f, destination: d, listeners: listeners, facts: httppolicy.AddressFacts{Complete: true, Addresses: append([]netip.Addr(nil), addresses...), GatewayListeners: append([]netip.AddrPort(nil), owned...)}}, nil
}

func (p *ProxyAddress) Facts() httppolicy.AddressFacts {
	return httppolicy.AddressFacts{Complete: p.facts.Complete, Addresses: append([]netip.Addr(nil), p.facts.Addresses...), GatewayListeners: append([]netip.AddrPort(nil), p.facts.GatewayListeners...)}
}

func (p *ProxyAddress) Dial(ctx context.Context, private bool) (net.Conn, error) {
	if p == nil || !p.used.CompareAndSwap(false, true) {
		return nil, ErrAddressPolicy
	}
	owned := p.listeners()
	if len(owned) > contract.HTTPAddressFacts {
		return nil, ErrAddressPolicy
	}
	for _, listener := range owned {
		if !listener.IsValid() || listener.Port() == 0 || listener.Addr().Zone() != "" {
			return nil, ErrAddressPolicy
		}
	}
	for _, ip := range p.facts.Addresses {
		class := httppolicy.ClassifyAddress(ip)
		if class == httppolicy.AddressForbidden || class == httppolicy.AddressPrivate && !private {
			return nil, ErrAddressPolicy
		}
		for _, listener := range owned {
			if ip.Unmap() == listener.Addr().Unmap() && p.destination.Port() == listener.Port() {
				return nil, ErrAddressPolicy
			}
		}
	}
	ctx, cancel := context.WithTimeout(ctx, contract.HTTPProxyDialTimeout)
	defer cancel()
	conn, err := p.factory.dial(ctx, "tcp", netip.AddrPortFrom(p.facts.Addresses[0], p.destination.Port()).String())
	if err != nil {
		return nil, ErrAddressPolicy
	}
	return &proxyIdleConn{Conn: conn}, nil
}

// ProxyExchange makes one fresh HTTP/1 upstream attempt. No pool, coalescing,
// redirect client or GetBody exists; the single-use dial also fences hidden
// transport redials. Client-facing intercepted H2 is independent of this hop.
func (p *ProxyAddress) ProxyExchange(ctx context.Context, target httppolicy.Request, header http.Header, body io.ReadCloser, length int64, private bool, roots *x509.CertPool) (*http.Response, error) {
	if p == nil || target.Destination() != p.destination || ValidateProxyHeaders(header) != nil {
		return nil, ErrInvalidURL
	}
	outgoing := header.Clone()
	outgoing.Set("Host", target.Destination().Authority())
	outgoing.Set("Connection", "close")
	// Budget transport-generated fields as well as the supplied header map.
	if body != nil {
		if length >= 0 {
			outgoing.Del("Transfer-Encoding")
			outgoing.Set("Content-Length", strconv.FormatInt(length, 10))
		} else {
			outgoing.Del("Content-Length")
			outgoing.Set("Transfer-Encoding", "chunked") //nolint:gosec // Budget-only map, never transmitted; mutually exclusive framing is generated by Transport.
		}
	}
	if _, present := outgoing["User-Agent"]; !present {
		outgoing.Set("User-Agent", "Go-http-client/1.1")
	}
	if ValidateProxyHeaders(outgoing) != nil {
		return nil, ErrResponseLimit
	}
	protocols := new(http.Protocols)
	protocols.SetHTTP1(true)
	transport := &http.Transport{Protocols: protocols, Proxy: nil, DisableKeepAlives: true, DisableCompression: true, ForceAttemptHTTP2: false, MaxResponseHeaderBytes: contract.HTTPProxyHeaderBytes, TLSHandshakeTimeout: contract.HTTPProxyDialTimeout, ResponseHeaderTimeout: contract.HTTPProxyHeaderTimeout,
		DialContext:     func(ctx context.Context, _, _ string) (net.Conn, error) { return p.Dial(ctx, private) },
		TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12, ServerName: p.destination.Host(), RootCAs: roots}, //nolint:gosec // Verification remains enabled, with platform roots in production.
	}
	req := &http.Request{Method: target.Method(), URL: target.URL(), Host: target.Destination().Authority(), Header: header.Clone(), Body: body, ContentLength: length, Close: true}
	requestCtx, cancel := context.WithCancel(ctx)
	req = req.WithContext(requestCtx)
	response, err := transport.RoundTrip(req)
	if err != nil {
		cancel()
		transport.CloseIdleConnections()
		return nil, ErrAddressPolicy
	}
	if response.StatusCode == http.StatusSwitchingProtocols || ValidateProxyHeaders(response.Header) != nil {
		cancel()
		_ = response.Body.Close()
		transport.CloseIdleConnections()
		return nil, ErrResponseLimit
	}
	response.Body = &responseBody{ReadCloser: response.Body, transport: transport, cancel: cancel}
	return response, nil
}

func ValidateProxyHeaders(header http.Header) error { return validateHeaders(header) }

type proxyIdleConn struct{ net.Conn }

func (c *proxyIdleConn) CloseWrite() error {
	if half, ok := c.Conn.(interface{ CloseWrite() error }); ok {
		return half.CloseWrite()
	}
	return c.Close()
}

func (c *proxyIdleConn) Read(b []byte) (int, error) {
	if err := c.SetReadDeadline(time.Now().Add(contract.HTTPProxyIdleTimeout)); err != nil {
		return 0, err
	}
	return c.Conn.Read(b)
}
func (c *proxyIdleConn) Write(b []byte) (int, error) {
	if err := c.SetWriteDeadline(time.Now().Add(contract.HTTPProxyIdleTimeout)); err != nil {
		return 0, err
	}
	return c.Conn.Write(b)
}
